language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install xdotool
install:
  - bash install.sh sunbeam anaconda_log.txt
  - bash install_igv.sh
script: bash tests/test.sh
#test
