channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - singularity
  - ruamel.yaml
  - biopython # Needed for building test data
  - kraken2 # Needed for building test data
  - semantic_version
  - wgsim
  - python>=3.10
