# 
# Sunbeam configuration file
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: "/home/chunyu/sunbeam-test" 
  data_fp: "data_files"
  output_fp: "sunbeam_output"
  filename_fmt: "PCMP_{sample}_{rp}.fastq.gz"
  subcores: 4
  exclude: []


# Quality control
qc:
  suffix: qc
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4,15]
  minlen: 36
  host: human
  pct_id: 0.5
  frac: 0.6
  keep_sam: True
  adapter_fp: "/home/chunyu/miniconda3/envs/sunbeam-test/share/trimmomatic/adapters/NexteraPE-PE.fa"


# Taxonomic classifications
classify:
  suffix: classify
  taxa_db_fp: ""
  clark_opts: "-m 0"
  clark_db_fp: ""
  clark_targets: "bacteria viruses human"
  clark_level: "species"
  clark_version: "CLARK-l"
  kraken_db_fp: "/home/common/kraken/standard"


# Contig assembly
assembly:
  suffix: assembly


# Contig annotation
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500

  
# Blast databases
blastdbs:
  root_fp: "/media/THING1-RO/local/genomeIndexes/blast"
  nucleotide:
    bacteria:
      BacterialGenomes/ncbi_bacteria.fa
    viral:
      viral.1.1.genomic.fna
    nt:
      nt/nt
  protein:
    integrase:
      UniprotPhageIntegrase.fasta
    aclame:
      ACLAME/aclame_proteins_viruses_prophages_0.4.fasta
    vfdb:
      VFDB/VFs.faa
#    card:
#      card/nucl_homolog.fasta

mapping:
  suffix: mapping
  genomes_fp: ""


