# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.5

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

      - run:
          name: install
          command: |
            bash install.sh -u lib -e sunbeam -m
          no_output_timeout: 20m

      - run:
          name: dump_env
          command: |
            bash .circleci/dump_conda_env.bash | tee /tmp/pkgs.txt

      - store_artifacts:
          path: /tmp/pkgs.txt
          destination: conda-env

      - run:
          name: run tests
          command: |
            bash tests/run_tests.bash -e sunbeam

      - save_cache:
          paths:
            - ~/miniconda3
          key: v3-dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

workflows:
  version: 2
  weeklybuild:
    triggers:
      - schedule:
          cron: "30 14 * * 3"
          filters:
            branches:
              only:
                - dev
                - stable
    jobs:
      - build
  default:
    jobs:
      - build
