# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: Build and push Docker image
          command: |
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            docker build -t ctbushman/sunbeam:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ctbushman/sunbeam:$TAG

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

      - run:
          name: install
          command: |
            bash install.sh -u lib -v
          no_output_timeout: 20m

      - run:
          name: dump_env
          command: |
            bash .circleci/dump_conda_env.bash

      - run:
          name: run tests
          command: |
            TAG=$(git describe --tag)
            bash tests/run_tests.bash -e sunbeam${TAG:1} -t all
          no_output_timeout: 40m

      - save_cache:
          paths:
            - ~/miniconda3
          key: v3-dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

workflows:
  version: 2
  weeklybuild:
    triggers:
      - schedule:
          cron: "30 14 * * 3"
          filters:
            branches:
              only:
                - dev
                - stable
    jobs:
      - build
  default:
    jobs:
      - build
