# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

      - run:
          name: install
          command: |
            bash install.sh -u lib -v
          no_output_timeout: 20m

      - run:
          name: dump_env
          command: |
            bash .circleci/dump_conda_env.bash
            bash dev_scripts/dump_.snakemake.sh

      - run:
          name: run tests
          command: |
            export PATH=$PATH:$HOME/miniconda3/bin
            CONDA_BASE=$(conda info --base)
            source $CONDA_BASE/etc/profile.d/conda.sh
            
            TAG=$(git describe --tag)
            conda activate sunbeam${TAG:1}
            pytest tests/ -vvl
          no_output_timeout: 40m

      - run:
          name: log dump
          when: always
          command: tail -n +1 output_*/sunbeam_output/logs/*

      - run:
          name: output tree dump
          when: always
          command: ls -lRh output_*
      
      - run:
          name: reports dump
          when: always
          command: cat output_*/sunbeam_output/qc/reports/preprocess_summary.tsv

      - run:
          name: benchmark dump
          when: always
          command: cat output_*/stats/*

      - save_cache:
          paths:
            - ~/miniconda3
          key: dependencies-{{ .Branch }}-{{ checksum "environment.yml" }}

workflows:
  version: 2
  weeklybuild:
    triggers:
      - schedule:
          cron: "30 14 * * 3"
          filters:
            branches:
              only:
                - dev
                - stable
    jobs:
      - build
  default:
    jobs:
      - build
